### ISSUE TITLE
Can we add links to GenBank for the features in the CDS and Genes tracks?

### ISSUE THREAD

**Issue by ihh** [GMOD/sars-cov-2-jbrowse#1]

**Comment by scottcain** [comment]
Done on master.

**Comment by nathandunn** [comment]
@rbuels  / @cmdcolin  

@scottcain  is still alive

**Comment by cmdcolin** [comment]
this was added to the other instance at http://s3.amazonaws.com/sars-cov-2-jbrowse/jbrowse/index.html?data=data%2FSARS-CoV-2&loc=NC_045512.2%3A1..29903&tracks=DNA%2CGenes&highlight= too now
